import { create } from "zustand";

const useAddEmpForm = create((set) => ({
  first_name: "",
  last_name: "",
  email: "",
  companyemail: "",
  password: "",
  date_of_birth: "",
  phone_number: "",
  address: "",
  gender: "",
  citizenship: "",
  joining_date: "",
  firstNameError: "",
  lastNameError: "",
  emailError: "",
  passwordError: "",
  companyEmailError: "",
  deptname: "",
  mgrempid: "",
  employmentType: "",
  designation: "",
  worklocation: "",
  salarystructure: "",
  adhar_card_number: "",
  pan_card_number: "",
  dept_cost_center_no: "",

  setFirstName: (first_name) => set({ first_name }),
  setLastName: (last_name) => set({ last_name }),
  setEmail: (email) => set({ email }),
  setGender: (gender) => set({ gender }),
  setCompanyEmail: (companyemail) => set({ companyemail }),
  setPassword: (password) => set({ password }),
  setPhoneNumber: (phone_number) => set({ phone_number }),
  setAddress: (address) => set({ address }),
  setCitizenShip: (citizenship) => set({ citizenship }),
  setJoiningDate: (joining_date) => set({ joining_date }),
  setDateOfBirth: (date_of_birth) => set({ date_of_birth }),
  setAdharCardNumber: (adhar_card_number) => set({ adhar_card_number }),
  setPanCardNumber: (pan_card_number) => set({ pan_card_number }),
  setFirstNameError: (error) => set({ firstNameError: error }),
  setLastNameError: (error) => set({ lastNameError: error }),
  setEmailError: (error) => set({ emailError: error }),
  setPasswordError: (error) => set({ passwordError: error }),
  setCompanyEmailError: (error) => set({ companyEmailError: error }),
  setDeptName: (deptname) => set({ deptname }),
  setMgrEmpId: (mgrempid) => set({ mgrempid }),
  setEmploymentType: (employmentType) => set({ employmentType }),
  setSalaryStructure: (salarystructure) => set({ salarystructure }),
  setWorkLocation: (worklocation) => set({ worklocation }),
  setDesignation: (designation) => set({ designation }),
  setDeptCostCenterNo: (dept_cost_center_no) => set({ dept_cost_center_no }),
}));

export default useAddEmpForm;
