import { create } from "zustand";

const useEmpState = create((set) => {
  return {
    first_name: undefined,
    last_name: undefined,
    email: undefined,
    phone_number: undefined,
    address: undefined,
    citizenship: undefined,
    adhar_card_number: undefined,
    pan_card_number: undefined,
    gender: undefined,
    bank_account_no: undefined,
    date_of_birth: undefined,
    password: undefined,
    confirmPassword: undefined,
    designation: undefined,
    worklocation: undefined,
    deptname: undefined,
    employmentType: undefined,
    empId: undefined,
    mgrempid: undefined,
    joining_date: undefined,
    salarystructure: undefined,
    dept_cost_center_no: undefined,
    companyemail: undefined,
    profile: [],
    shift_allocation: undefined,
    data: undefined,

    // setFirstName: ( first_name) => set({  first_name }),
    // setLastName: ( last_name) => set({  last_name }),
    // setEmail: (email) => set({ email }),
    // setPhoneNumber: ( phone_number) => set({  phone_number }),
    // setAddress: ( address) => set({  address }),
    // setCitizenship: ( citizenship) => set({  citizenship }),
    // setAdharCardNumber: ( adhar_card_number) => set({  adhar_card_number }),
    // setPanCardNumber: ( pan_card_number) => set({  pan_card_number }), 
    // setGender: ( gender) => set({  gender }),
    // setBankAccountNo: ( bank_account_no) => set({  bank_account_no }),
    // setDateOfBirth: (date_of_birth) => set({ date_of_birth }),
    // setPassword: ( password) => set({  password }),
    // setConfirmPassword: ( confirmPassword) => set({  confirmPassword }),
    // setDesignation: ( designation) => set({  designation }),
    // setWorkLocation: ( worklocation) => set({  worklocation }),
    // setDepartmentName: ( deptname) => set({  deptname }),
    // setEmploymentType: ( employmentType) => set({  employmentType }),
    // setEmpId: ( empId) => set({  empId }),
    // setMgrEmpId: (mgrempid) => set({ mgrempid }),
    // setJoiningDate: ( joining_date) => set({  joining_date }),
    // setSalaryStructure: (salarystructure) => set({ salarystructure }),
    // setDeptCostCenterNo: ( dept_cost_center_no) => set({  dept_cost_center_no }),
    // setCompanyEmail: (companyemail) => set({ companyemail }),
    // setProfile: (profile) => set({ profile }),
    // setShiftAllocation: (shift_allocation) => set({ shift_allocation }),
    
  };
});

export default useEmpState;
