name: Central Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment (dev, qa, prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  run-build:
    name: Build Job
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}  # Set dynamic environment based on input
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run build script for ${{ inputs.environment }}
        run: |
          echo "Running build for ${{ inputs.environment }}"

  run-sonarqube:
    name: SonarQube Code Analysis
    needs: run-build
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}  # Set dynamic environment based on input
    steps:
      - name: Run SonarQube Scan for ${{ inputs.environment }}
        uses: ./.github/workflows/SonarQube.yml
        with:
          SONAR_HOST_URL: http://13.202.182.26:9000
        secrets:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

  run-selenium:
    name: Run Selenium Tests
    needs: run-sonarqube
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}  # Set dynamic environment based on input
    steps:
      - name: Run Selenium Tests for ${{ inputs.environment }}
        uses: ./.github/workflows/Selenium.yml
        with:
          environment: ${{ inputs.environment }}  # Pass environment variable
