
name: Central Workflow

on:
  workflow_dispatch:  # 🚀 Manual trigger for the workflow

jobs:
  run-build:  # 🔧 Build Job
    # 🛠️ Step 1: Run the build pipeline
    uses: ./.github/workflows/build.yaml

  run-sonarqube:  # 🔍 SonarQube Code Analysis
    needs: run-build
    # 🧪 Step 2: Run static code analysis using SonarQube
    uses: ./.github/workflows/SonarQube.yml
    with:
      SONAR_HOST_URL: http://13.202.182.26:9000
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  run-selenium:  # 🧪 Selenium Tests
    needs: run-sonarqube
    # ✅ Step 3: Run end-to-end Selenium tests after SonarQube analysis
    uses: ./.github/workflows/Selenium.yml
