name: Central Workflow

on:
  workflow_dispatch:  # 🚀 Manual trigger for the workflow

jobs:
  run-build:  # 🔧 Build Job
    uses: ./.github/workflows/build.yaml

  run-sonarqube:  # 🔍 SonarQube Code Analysis
    needs: run-build
    uses: ./.github/workflows/SonarQube.yml
    with:
      SONAR_HOST_URL: http://13.202.182.26:9000
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

  run-selenium:  # 🧪 Selenium Tests
    needs: run-sonarqube
    uses: ./.github/workflows/Selenium.yml
